#spring:
#  datasource:
#    username: sa
#    password:
#    url: jdbc:h2:mem:ejercicio_java
#    driverClassName: org.h2.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
